<p style="margin:1.55pt 68.85pt 0pt 68.9pt; text-align:center; font-size:14pt;"><strong>BERITA</strong><strong><span style="letter-spacing:-0.2pt;">&nbsp;</span></strong><strong>ACARA</strong><strong><span style="letter-spacing:-0.1pt;">&nbsp;</span></strong><strong>PEMILIHAN</strong><strong><span style="letter-spacing:-0.15pt;">&nbsp;</span></strong><strong>KETUA</strong><strong><span style="letter-spacing:-0.1pt;">&nbsp;</span></strong><strong>DAN</strong><strong><span style="letter-spacing:-0.2pt;">&nbsp;</span></strong><strong>WAKIL</strong><strong><span style="letter-spacing:-0.25pt;">&nbsp;</span></strong><strong>KETUA</strong><strong><span style="letter-spacing:-0.1pt;">&nbsp;</span></strong><strong><span style="letter-spacing:-0.2pt;">OSIS</span></strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:14pt;"><strong>&nbsp;</strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:20.5pt;"><strong>&nbsp;</strong></p>
<p style="margin:0pt 5.1pt 0pt 5pt; text-align:justify; line-height:115%; font-size:12pt;">Pada Hari ini&nbsp; Rabu Tanggal Empat Belas Bulan Februari Tahun Dua Ribu Dua Puluh Tiga<span style="letter-spacing:2pt;">&nbsp;</span>bertempat di SMAN 1 Margaasih telah dilaksanakan pemilihan ketua OSIS untuk<span style="letter-spacing:2pt;">&nbsp;</span>masa bakti 2023/2024 dengan hasil perolehan suara sebagai berikut :</p>
<ol style="margin:0pt; padding-left:0pt;" type="1">
    <li style="margin-top:10.05pt; margin-left:37.06pt; padding-left:3.94pt; font-size:12pt;">Azhar Fatwa Nugraha&nbsp;&amp; Rameyshanda Pudjianti Putri<span style="width:39.87pt; display:inline-block;">&nbsp;</span><span style="letter-spacing:-0.5pt;">: <?= $pil1 ?></span><span style="width:24.51pt; display:inline-block;">&nbsp;</span><span style="letter-spacing:-0.1pt;">Suara</span></li>
    <li style="margin-top:2.15pt; margin-left:37.06pt; padding-left:3.94pt; font-size:12pt; letter-spacing:-0.1pt;"><span style="letter-spacing:normal;">Aditya Pasha Priwardhana</span><span style="letter-spacing:-0.15pt;">&nbsp;</span><span style="letter-spacing:normal;">&amp;</span> <span style="letter-spacing:normal;">Sherla Devita</span><span style="width:94.69pt; display:inline-block;">&nbsp;</span><span style="letter-spacing:-0.5pt;">: <?= $pil2 ?></span><span style="width:24.51pt; display:inline-block;">&nbsp;</span>Suara</li>
    <li style="margin-top:2.15pt; margin-right:140.6pt; margin-left:5pt; text-indent:18pt; line-height:184%; font-size:12pt; list-style-position:inside;"><span style="width:3.94pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;</span><span style="letter-spacing:-0.1pt;"></span>Catatan lain selama pemilihan berlangsung :</li>
</ol>
<p style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; line-height:14.55pt;"><span style="font-size:12pt; letter-spacing:-0.1pt;">&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;</span></p>
<p style="margin-top:2.2pt; margin-left:5pt; margin-bottom:0pt; font-size:12pt;">Jumlah Pemilih: <?= $jumlahPemilih ?> Siswa/Siswi<span style="letter-spacing:-0.1pt;">&hellip;&hellip;.&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;</span></p>
<p style="margin-top:2.15pt; margin-left:5pt; margin-bottom:0pt; font-size:12pt;">Jumlah Yang Memilih: <?= $sudah ?> Siswa/Siswi<span style="letter-spacing:-0.1pt;">&hellip;&hellip;&hellip;&hellip;.&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;</span></p>
<p style="margin-top:2.15pt; margin-left:5pt; margin-bottom:0pt; font-size:12pt;">Jumlah Yang Tidak Memilih: <?= $belum ?> Siswa/Siswi<span style="letter-spacing:-0.1pt;">&hellip;&hellip;&hellip;&hellip;.&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;</span></p>
<p style="margin-top:2.25pt; margin-left:5pt; margin-bottom:0pt; line-height:184%; font-size:12pt;"><span style="letter-spacing:-0.1pt;">&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;.&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&hellip;&nbsp;</span><br>Demikian berita acara ini dibuat untuk dapat dipergunakan sebagaimana mestinya.</p>
<p style="margin:0pt 68.85pt; text-align:center; line-height:14.4pt;"><span style="font-size:12pt;">CALON KETUA</span><span style="font-size:12pt; letter-spacing:-0.15pt;">&nbsp;</span><span style="font-size:12pt;">&amp;</span><span style="font-size:12pt; letter-spacing:-0.1pt;">&nbsp;</span><span style="font-size:12pt;">WAKIL</span><span style="font-size:12pt; letter-spacing:-0.2pt;">&nbsp;</span><span style="font-size:12pt;">KETUA</span><span style="font-size:12pt; letter-spacing:-0.1pt;">&nbsp;</span><span style="font-size:12pt; letter-spacing:-0.5pt;">:</span></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt;">&nbsp;</p>
<ol start="1" style="margin:0pt; padding-left:0pt;">
    <li style="margin-left:19.24pt; padding-left:3.76pt; font-size:12pt; font-weight:bold;"><span style="font-weight:normal;">Azhar Fatwa Nugraha</span><span style="width:43.41pt; display:inline-block;">&nbsp;</span><span style="font-weight:normal;">:&nbsp;</span><u><span style="width:76.73pt; font-family:'arial'; font-weight:normal; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></u></li>

<p style="margin-top:0.05pt; margin-bottom:0pt; font-size:13.5pt;">&nbsp;</p>

    <li style="margin-top:2.6pt; margin-left:19.24pt; padding-left:3.76pt; font-size:12pt; font-weight:bold;"><span style="font-weight:normal;">Rameyshanda Pudjianti Putri</span><span style="width:61.87pt; display:inline-block;">&nbsp;</span><span style="font-weight:normal;">:&nbsp;</span><u><span style="width:76.73pt; font-family:'arial'; font-weight:normal; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></u></li>

<p style="margin-top:0.5pt; margin-bottom:0pt; font-size:13pt;">&nbsp;</p>

    <li style="margin-top:2.55pt; margin-left:19.24pt; padding-left:3.76pt; font-size:12pt; font-weight:bold;"><span style="font-weight:normal;">Aditya Pasha Priwardhana</span><span style="width:76.53pt; display:inline-block;">&nbsp;</span><span style="font-weight:normal;">:&nbsp;</span><u><span style="width:76.73pt; font-family:'arial'; font-weight:normal; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></u></li>

<p style="margin-top:0.05pt; margin-bottom:0pt; font-size:13.5pt;">&nbsp;</p>

    <li style="margin-top:2.55pt; margin-left:19.24pt; padding-left:3.76pt; font-size:12pt; font-weight:bold;"><span style="font-weight:normal;">Sherla Devita</span><span style="width:83.57pt; display:inline-block;">&nbsp;</span><span style="font-weight:normal;">:&nbsp;</span><u><span style="width:76.73pt; font-family:'arial'; font-weight:normal; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></u></li>
</ol>
<p style="margin-top:2.15pt; margin-left:23pt; margin-bottom:0pt; text-indent:-18.05pt; font-size:10pt;"><strong>&nbsp;</strong></p>
<p style="margin-top:2.55pt; margin-left:23pt; margin-bottom:0pt; font-size:10pt;"><strong>&nbsp;</strong></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:10pt;"><strong>&nbsp;</strong></p>
<p style="margin-top:0.4pt; margin-bottom:0pt; font-size:9.5pt;"><strong>&nbsp;</strong></p>
<p style="margin:2.6pt 159.9pt 0pt 160.05pt; text-align:center; line-height:184%; font-size:12pt;">PANITIA<span style="letter-spacing:-0.55pt;">&nbsp;</span>PEMILIHAN<span style="letter-spacing:-0.5pt;">&nbsp;</span>KETUA<span style="letter-spacing:-0.5pt;">&nbsp;</span>OSIS <span style="letter-spacing:-0.1pt;">KETUA</span></p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;">&nbsp;</p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;">&nbsp;</p>
<p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;">&nbsp;</p>
<p style="margin:9.55pt 68.85pt 0pt 68.8pt; text-align:center; font-size:12pt;"><strong>__________________</strong></p>
